# Generated by Django 3.0.6 on 2020-05-26 16:28

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(18)])),
                ('sexe', models.CharField(blank=True, choices=[('FEMME', 'Femme'), ('HOMME', 'Homme'), ('NON_BINAIRE', 'Non binaire')], default='FEMME', max_length=11, null=True)),
                ('taille', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(250), django.core.validators.MinValueValidator(80)])),
                ('poids', models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(0)])),
                ('objectif_poids', models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(20)])),
                ('expected_calories', models.IntegerField(blank=True, null=True)),
                ('allergies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('LACTOSE', 'Lactose'), ('GLUTEN', 'Gluten'), ('VEGETARIEN', 'Végétarien'), ('ARACHIDES', 'Arachides'), ('FRUITS_DE_MER', 'Fruits de mer')], max_length=32, null=True), blank=True, default=list, size=None)),
                ('diabetique', models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
