export const AuthTypes = {
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    CHANGE_PASSWORD: "CHANGE_PASSWORD",
    USER_PROFILE: "USER_PROFILE",
    GET_HEALTH_DATA: "GET_HEALTH_DATA",
    UPDATE_HEALTH_DATA: "UPDATE_HEALTH_DATA", 
};

export const MessTypes = {
    CREATE_MESSAGE: "CREATE_MESSAGE",
    GET_ERRORS: "GET_ERRORS",

};

export const ProdTypes = {
    GET_PRODUCTS: "GET_PRODUCTS",
    FIND_PRODUCTS: "FIND_PRODUCTS",
    PRODUCT_DETAILS: "PRODUCT_DETAILS"

};

export const CalTypes = {
    GET_BREAKFAST: "GET_BREAKFAST",
    GET_DINNER: "GET_DINNER",
    GET_LUNCH: "GET_LUNCH",
    ADD_MEAL: "ADD_MEAL",
    EDIT_MEAL: "EDIT_MEAL",
    DELETE_MEAL: "DELETE_MEAL",
    GET_CALORIES: "GET_CALORIES",
    UPDATE_CALORIES: "UPDATE_CALORIES",
    GET_WEIGHT: "GET_WEIGHT",
    UPDATE_WEIGHT: "UPDATE_WEIGHT",
};
