# Generated by Django 3.0.6 on 2020-06-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0002_auto_20200602_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='additives_n',
        ),
        migrations.RemoveField(
            model_name='products',
            name='fruits_vegetables_nuts_100g',
        ),
        migrations.RemoveField(
            model_name='products',
            name='ingredients_from_palm_oil_n',
        ),
        migrations.RemoveField(
            model_name='products',
            name='salt_100g',
        ),
        migrations.AddField(
            model_name='products',
            name='energy_kj_100g',
            field=models.FloatField(blank=True, db_column='energy-kj_100g', null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='glycemic_index_100g',
            field=models.FloatField(blank=True, db_column='glycemic-index_100g', null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='main_category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='traces_tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
