export const GET_MESSAGES = "GET_MESSAGES";
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const FIND_PRODUCTS = "FIND_PRODUCTS";
export const PRODUCT_DETAILS = "PRODUCT_DETAILS";