# Generated by Django 3.0.6 on 2020-05-19 20:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(18)])),
                ('sexe', models.CharField(choices=[('F', 'Femme'), ('H', 'Homme'), ('NB', 'Non binaire')], default='F', max_length=3)),
                ('taille', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(250), django.core.validators.MinValueValidator(80)])),
                ('poids', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(0)])),
                ('objectif_poids', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(20)])),
                ('expected_calories', models.IntegerField(default=2000)),
                ('allergies', models.CharField(choices=[('LAC', 'Lactose'), ('GLU', 'Gluten'), ('VEL', 'Végétalien'), ('VER', 'Végétarien'), ('ARA', 'Arachides'), ('FDM', 'Fruits de mer')], max_length=4, null=True)),
                ('diabetique', models.BooleanField(default=False)),
            ],
        ),
    ]
