# Generated by Django 3.0.6 on 2020-05-20 17:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Infos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(18)])),
                ('sexe', models.CharField(choices=[('FEMME', 'Femme'), ('HOMME', 'Homme'), ('NON BINAIRE', 'Non binaire')], default='FEMME', max_length=11)),
                ('taille', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(250), django.core.validators.MinValueValidator(80)])),
                ('poids', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(0)])),
                ('objectif_poids', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(20)])),
                ('expected_calories', models.IntegerField(default=2000)),
                ('allergies', models.CharField(blank=True, choices=[('LACTOSE', 'Lactose'), ('GLUTEN', 'Gluten'), ('VEGETALIEN', 'Végétalien'), ('VEGETARIEN', 'Végétarien'), ('ARACHIDES', 'Arachides'), ('FRUITS DE MER', 'Fruits de mer')], max_length=20, null=True)),
                ('diabetique', models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non')], max_length=5)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
