# Generated by Django 3.0.6 on 2020-05-21 13:38

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infos',
            name='allergies',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('LACTOSE', 'Lactose'), ('GLUTEN', 'Gluten'), ('VEGETALIEN', 'Végétalien'), ('VEGETARIEN', 'Végétarien'), ('ARACHIDES', 'Arachides'), ('FRUITS DE MER', 'Fruits de mer')], max_length=60, null=True),
        ),
    ]
