# Generated by Django 3.0.6 on 2020-05-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infos',
            name='allergies',
            field=models.CharField(blank=True, choices=[('LAC', 'Lactose'), ('GLU', 'Gluten'), ('VEL', 'Végétalien'), ('VER', 'Végétarien'), ('ARA', 'Arachides'), ('FDM', 'Fruits de mer')], max_length=4, null=True),
        ),
    ]
