# Generated by Django 3.0.6 on 2020-05-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0002_auto_20200520_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infos',
            name='diabetique',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'Non')], max_length=1),
        ),
    ]
