# Generated by Django 3.0.6 on 2020-05-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0003_auto_20200520_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infos',
            name='diabetique',
            field=models.CharField(choices=[('O', 'Oui'), ('N', 'Non')], max_length=1),
        ),
    ]
