# Generated by Django 3.0.6 on 2020-05-25 08:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0003_auto_20200525_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infos',
            name='diabetique',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('OUI', 'Oui'), ('NON', 'Non')], max_length=10), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='infos',
            name='sexe',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('FEMME', 'Femme'), ('HOMME', 'Homme'), ('NON BINAIRE', 'Non binaire')], max_length=11), blank=True, default=list, size=None),
        ),
    ]
