# Generated by Django 3.0.6 on 2020-05-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0004_auto_20200525_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infos',
            name='diabetique',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non')], max_length=5),
        ),
        migrations.AlterField(
            model_name='infos',
            name='sexe',
            field=models.CharField(choices=[('FEMME', 'Femme'), ('HOMME', 'Homme'), ('NON BINAIRE', 'Non binaire')], default='FEMME', max_length=11),
        ),
    ]
