# Generated by Django 3.0.6 on 2020-05-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0004_auto_20200520_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infos',
            name='allergies',
            field=models.CharField(blank=True, choices=[('LACTOSE', 'Lactose'), ('GLUTEN', 'Gluten'), ('VEGETALIEN', 'Végétalien'), ('VEGETARIEN', 'Végétarien'), ('ARACHIDES', 'Arachides'), ('FRUITS DE MER', 'Fruits de mer')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='infos',
            name='diabetique',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non')], max_length=5),
        ),
        migrations.AlterField(
            model_name='infos',
            name='sexe',
            field=models.CharField(choices=[('FEMME', 'Femme'), ('HOMME', 'Homme'), ('NON BINAIRE', 'Non binaire')], default='FEMME', max_length=11),
        ),
    ]
