# Generated by Django 3.0.6 on 2020-05-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0005_auto_20200525_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infos',
            name='sexe',
            field=models.CharField(choices=[('FEMME', 'Femme'), ('HOMME', 'Homme'), ('NON_BINAIRE', 'Non binaire')], default='FEMME', max_length=11),
        ),
    ]
