# Generated by Django 3.0.6 on 2020-05-18 12:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users_Infos',
            new_name='Infos',
        ),
        migrations.RenameField(
            model_name='infos',
            old_name='user_id',
            new_name='user',
        ),
    ]
